use_frameworks!

target 'PayMESDK_Example' do
  pod 'PayMESDK', :path => '../'

  target 'PayMESDK_Tests' do
    inherit! :search_paths
    pod 'CryptoSwift', '~> 1.0'
    pod 'SwiftyRSA', '1.5'
    
  end
end
